# Generated by Django 3.1.7 on 2021-02-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='esp8266Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
