# Generated by Django 3.1.7 on 2021-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp8266test',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
