# Generated by Django 3.1.7 on 2021-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardim', '0002_auto_20210227_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pre_umidade_solo', models.IntegerField(blank=True, null=True)),
                ('pos_umidade_solo', models.IntegerField(blank=True, null=True)),
                ('tempo_rega_segundos', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
