# Generated by Django 3.1.7 on 2021-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardim', '0003_regas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pre_soil_humidity', models.IntegerField(blank=True, null=True)),
                ('after_soil_humidity', models.IntegerField(blank=True, null=True)),
                ('watering_time_seconds', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Regas',
        ),
    ]
