# Generated by Django 3.1.7 on 2021-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardim', '0004_auto_20210301_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
