# Generated by Django 3.1.7 on 2021-03-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardim', '0005_auto_20210301_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='esp8266Test',
        ),
    ]
